### ISSUE TITLE
[FEATURE] establish multiple select and Copy/Paste

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#11]
pretty important for the preset creation workflow is the ability, to:
1. Select one or several elements on the screen (optionally by pulling a frame around them or by shift+click)
2. make Copy and Paste available
...for example to copy a set of elements from one page to another.

**Comment by TimSusa** [comment]
# Possible Algorithm
- A First step could be to make the field "lastFocusedIndex" store more than one value as an array
- Values are added to the array, if some hotkey is pressed inkl click to the new element 
- If more than element was selected, it is automatically saved to clipboard
- Now any element could be anew focused and afterwards cmd + v can be pressed or a mous-click is available to cut out all elements and input them at the location right to another

# Caveats
- The full order of all elements could be damaged, as a result you have to go back, all is lost
- An extra algorithm has to be invented, which orders the input of selected elements the right way (could get very complex)
- A new alternative concept to make drag and drop possible, has to be found (find a new library, build stuff yourself)

**Comment by alectroniq** [comment]
established in 1.2.8-alpha.14
