### ISSUE TITLE
[BUG] slider behaviour broken

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#116]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.1.80 (started with 1.0.49)

**Describe the bug**
Sliders hardly move. When touching a slider, it keeps lit (or marked), just like i wouldn't release my finger. 
! When moving the mouse curser over the marked slider, the slider follows the mouse cursor smoothly. 

**Desktop Version (please complete the following information):**
 - OS: Win 8, Win 10
 - Browser: Chrome

**Additional context**

**Comment by TimSusa** [comment]
should be fixed with v1.1.82
