### ISSUE TITLE
BUG - midi-bricks-persisted-app-settings.json incorrect

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#143]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] I do not know nor understand

**Can you determine, which version was used?**
Version: 1.2.3

**Describe the bug**
the file contains only the text "null"

**solved:**
replaced the file with yours, worked

**Comment by TimSusa** [comment]
I have a fix...

**Comment by TimSusa** [comment]
fix in v.1.2.5: https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.2.5
