### ISSUE TITLE
BUG - Lock Initial Window Pos/Size - data entry

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#145]
**Can you determine, which version was used?**
Version: 1.2.5

**Describe the bug**
When I try to enter window position and size, the entry field gets locked and greyed out after pressing just one key. I need to unlock the field again for every further digit. 

**Steps To Reproduce**
1. Go to 'Views Settings' --> 'View Settings'
2. Unlock 'Lock Initial Window....'
3. Enter number

**Expected behavior**
Normal data entry.

**Desktop Version (please complete the following information):**
 - OS: Win 10

**Comment by alectroniq** [comment]
issue still persists in 1.2.8

**Comment by TimSusa** [comment]
should be fixed in 1.3.0
