### ISSUE TITLE
BUG - Load Preset doesn't work

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#147]
**Does the issue occur in the electron-app or the web-app?**
- [x] midi-bricks-electron
- [ ] midi-bricks-web-app

**Can you determine, which version was used?**
Version: 1.2.5

**Describe the bug**
The app doesn't load my preset, which was created under 0.14.7 and still was loaded under 1.1.8x

**Steps To Reproduce**
1. Load a preset
2. Nothing happens after loading. 

**Expected behavior**
Load preset ;) 

**Desktop Version (please complete the following information):**
 - OS: Win10

**Comment by TimSusa** [comment]
As it seems to me, the app does not like js files anymore. But JSON does work here fine. Would you try to rename your preset to json? Does that work? I mean js files are not the way we want to go in the future...

**Comment by alectroniq** [comment]
I renamed my preset file from .js to .json, but v1.2.6 doesn't open it as well :(

**Comment by TimSusa** [comment]
It probably is not in JSON format. For anybody who reads this: https://jsoneditoronline.org/ could help or otherwise send me your preset via dropbox!

**Comment by TimSusa** [comment]
I found a way to load old presets. Should be fixed with 1.2.8: https://github.com/TimSusa/midi-bricks-mono/pull/152 would you please try?

**Comment by alectroniq** [comment]
Loading old presets works fine in 1.2.8. 
Both work: .js and .json
