### ISSUE TITLE
BUG - no auto update nor Views Settings changeable in 1.2.5

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#154]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [x] midi-bricks-web-app

**Can you determine, which version was used?**
Version: 1.2.5

**Describe the bug**
Automatic Update doesn't start on startup. 
Also, when trying to reset the Views Settings, it's not possible to change their settings. Switches won't move. 

**Steps To Reproduce**
1. open app --> no update
2. Click on 'Views Settings'
3. Try to switch settings

**Desktop Version (please complete the following information):**
 - OS: Win 8.1 64bit

**Comment by TimSusa** [comment]
Updates are not intended for the web-app. Furthermore, if using electron-app the first time, all settings have to be synchronized, through just clicking to all available settings. You can observe behaviour from the logs. Afterwards, update-settings should work.
