### ISSUE TITLE
BUG - horizontal slider: strange layout

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#155]
**Does the issue occur in the electron-app or the web-app?**
- [x] midi-bricks-electron only
- [ ] midi-bricks-web-app

**Can you determine, which version was used?**
Version: 1.2.9

**Describe the bug**
see screenshot below: adding a horizontal slider results in a slider, that has a button on his bottom

**Steps To Reproduce**
1. Go to Layout Mode
2. Add horizontal slider
3. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43702087/58466633-4fe4ed00-813a-11e9-84d8-287b2cca0dc5.png)

**Desktop Version (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome (no such behaviour in Chrome web-app, neither on Desktop nor on Android)

**Smartphone Version (please complete the following information):**
 - Device: HTC one m8
 - OS: Lineage OS
 - Browser: Chrome

**Comment by alectroniq** [comment]
I think this is still the most important issue to solve, before going public with the App.

**Comment by TimSusa** [comment]
fixed
