### ISSUE TITLE
FEATURE - App name

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#159]
Before we go public: Let's finally find a good name, that doesn't make it too complicated. It should be super easy to google it. 

If we keep the "Bricks" thing, my favoured suggestions: 
- MIDI Brikks
- MIDI Briqqs
...or just stay with MIDI Bricks

Of course open for very different suggestions! :)

**Comment by TimSusa** [comment]
..or just stay with MIDI Bricks
