### ISSUE TITLE
FEATURE - Add Elements in Layout Mode: introduce pictrograms

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#161]
To make it more user friendly, we should introduce small pictrograms (matching the Font Size of the menu). Maybe just create them from screenshots? 
If it's possible to insert graphs (instead of font symbols) to the menu, I could create these graphs here.

**Comment by TimSusa** [comment]
Feel free to provide. SVG would be fantastic. Screenshots or jpg other stuff is mostly some kind of ugly looking.

**Comment by TimSusa** [comment]
So there is no progress on this. I close the issue. Feel free to reopen, if some svg is more clear.
