### ISSUE TITLE
FEATURE - Groups 

### ISSUE THREAD

**Issue by patoche987** [TimSusa/midi-bricks-mono#172]
Hello, 
I want to control Ableton Live .
Can we add a notion of group  , to turn on or off a series of buttons ?
Example:
When the button is pressed, it turns off the other buttons in the group.

Patrick

**Comment by TimSusa** [comment]
Hi, 

You could achieve this already by just adressing more than one CC Value or Note. Please have a look at https://timsusa.github.io/midi-bricks-mono/ for further information at the help section.

When opening the Output Settings for an element, you can easily add those values via removable "Chips". 

Was this helpful for you? Please give me feedback.

**Comment by patoche987** [comment]
Hi
I will test as soon as possible with the new version  .
Patrick

**Comment by patoche987** [comment]
Configuration : I7+touchscreen Acer + other screen + ableton +VST's+ Yamaha promix + launchpad + 88 keys

**Comment by patoche987** [comment]
In fact i want to replace the launchpad by the touchscreen...
