### ISSUE TITLE
BUG - Slider Min/Max Values

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#173]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.18

**Describe the bug**
There are two related bugs: 

- A Slider with a defined value range (via _Maximum Value_ and _Minimum Value_ in the Slider's Settings dialog) gets limited to that range in its Slider track (physically): It stops on the Minimum Value limit. Expected behaviour: The set value range should be scaled to the full Slider track. But this doesn't occur on the Maximum Value, which is scaled up to the top correctly. 

- When mapped a MIDI Input to a Slider with such a defined value range, the input makes the Slider thumb "fly" over the Slider track, as soon as the set Min/Max Values are reached.

**Comment by TimSusa** [comment]
should be fixed with 1.3.21

**Comment by alectroniq** [comment]
Great, the sliders are scaled now to the full range. 
But will the swap of the Min/Max values of the horizontal sliders be fixed? 

Bug part 2 is moved into new issue #177

**Comment by TimSusa** [comment]
fixed 1.3.22. open up another issue for further stuff.
