### ISSUE TITLE
BUG - MIDI Input exceeds Sliders' Min/Max values

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#177]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.21

**Describe the bug**
When a MIDI Input is mapped to a Slider with a defined Min/Max Value range, the Slider thumb "flies" over the Slider track, as soon as the set Min/Max Value is reached. 

**Steps To Reproduce**
1. Create a Slider and go to Settings.
2. Set Min Value e.g. to 50.
3. Set Max Value eg. to 70. 
4. Map an external MIDI Controller input to this Slider.
5. Give MIDI Input from the external Controller and see thumb pass the limits. 

**Expected behavior**
Slider thumb shall not pass the limits.

**Comment by TimSusa** [comment]
fixed with 1.3.22
