### ISSUE TITLE
BUG - BUTTON_TOGGLE_CC send false OFF values

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#180]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.26
(worked fine before in v1.3.21)

**Describe the bug**
BUTTON_TOGGLE_CC send incorrect OFF values: they resend the ON values, not the defined OFF value. Additionally they don't give visual feedback. 

**Steps To Reproduce**
1. toggle a BUTTON_TOGGLE_CC on
2. toggle off
3. check MIDI data: sent OFF value equals the ON value
4. see missing visual feedback (on/off state)

**Comment by TimSusa** [comment]
Fixed with https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.3.27
