### ISSUE TITLE
BUG - in 1.3.28 

### ISSUE THREAD

**Issue by patoche987** [TimSusa/midi-bricks-mono#182]
nothing works anymore

![Capture](https://user-images.githubusercontent.com/54764879/67157236-bbb63500-f329-11e9-948e-91a04544386e.JPG)

**Comment by patoche987** [comment]
at the beginning I was able to test the new version. I had the round trip between it and Ableton. But nothing more is working.I reinstalled 1.3.23 and 1.3.28 from below.Same result

**Comment by alectroniq** [comment]
Have you tried at Development Console --> Application --> Clear Storage --> "clear site data" --> Page Refresh? This should help.

**Comment by patoche987** [comment]
hi 


it works 


i test this version 

----- Mail original -----

De: "alectroniq" <notifications@github.com> 
À: "TimSusa/midi-bricks-mono" <midi-bricks-mono@noreply.github.com> 
Cc: "patoche987" <patrick.rebullida@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 21 Octobre 2019 14:40:18 
Objet: Re: [TimSusa/midi-bricks-mono] BUG - in 1.3.28 (#182) 


Have you tried at Development Console --> Application --> Clear Storage --> "clear site data" --> Page Refresh? This should help.

**Comment by patoche987** [comment]
![IMG_20191021_220354](https://user-images.githubusercontent.com/54764879/67267250-2f834980-f4b2-11e9-9e1a-fce7a4696944.jpg)
![IMG_20191021_220354 (1)](https://user-images.githubusercontent.com/54764879/67267251-301be000-f4b2-11e9-9020-5be640ad1665.jpg)

It works better (see picture)

But i have a white screen when i changed the type of button  


Patrick 

----- Mail original -----

De: "alectroniq" <notifications@github.com> 
À: "TimSusa/midi-bricks-mono" <midi-bricks-mono@noreply.github.com> 
Cc: "patoche987" <patrick.rebullida@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 21 Octobre 2019 14:40:18 
Objet: Re: [TimSusa/midi-bricks-mono] BUG - in 1.3.28 (#182) 


Have you tried at Development Console --> Application --> Clear Storage --> "clear site data" --> Page Refresh? This should help.

**Comment by patoche987** [comment]
https://youtu.be/KZk3QCqm930

**Comment by TimSusa** [comment]
I could re-produce the crash! I have a fix. Should be fixed in 1.3.29

**Comment by TimSusa** [comment]
@patoche987 Could you please verify, that the crash is fixed? Otherwise please reopen this issue. Thx!
