### ISSUE TITLE
BUG - MIDI Input listener performing poorly 

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#183]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.27

**Describe the bug**
A slider follows incoming MIDI data only very slow and delayed, especially with more than 2-3 sliders in the layout.  

**Steps To Reproduce**
1. Create at least 2-3 sliders
2. map external MIDI CC to the sliders' inputs
3. move external controls and see sliders' response

**Comment by alectroniq** [comment]
I noticed that the bad performance only happens after loading a preset, no matter if in Live Mode or not. When I open the App and just use it in it's latest state, the silders follow incoming MIDI pretty well and quick!

**Comment by TimSusa** [comment]
As you can see I merged a PR which adresses this problem. Could you please try out version https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.3.37 if things went better? In my case I had very good results.

**Comment by alectroniq** [comment]
This performs very well now in 1.3.38-alpha.2 (sorry, I wasn't able to test earlier): 
Open the App, load a preset, navigate to a page, screw some mapped MIDI knobs - yepp, sliders responding quickly. 

But I recognize one fact: if you then navigate to other pages and back, the feedback performance slowly starts to decrease. After navigating back and forth the performance drops step by step, the sliders take gradually longer and longer to respond.  
I unknowingly observed this in many versions before, but I think this process of decreasing occured more quickly in earlier versions.

**Comment by alectroniq** [comment]
...oberved this in "normal" mode and in LIVE mode equally.

**Comment by TimSusa** [comment]
should be fixed with 1.3.38

**Comment by alectroniq** [comment]
It is! Performance is absolutely direct and quick, nothing to complain about. 
Also I cannot reproduce the deterioration that I mentioned before. Well done - thx so much!
