### ISSUE TITLE
BUG - Settings Mode: multiple Elements selection / editing Elements

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#184]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.27

**Describe the bug**
When editing settings of Elements in the Settings Mode, clicking on an Element selects it. When trying to edit another Element, it gets multiple-selected with the previous one - which makes editing impossible without killing settings of the previously edited Element. Also it's not possible to de-select Elements. 
The only way to work around, is to leave Settings Mode after every setting. That's not logical and will drive users mad. 

**ideas, options**
- apply selection of Elements only in a dedicated "select" or "copy & paste" mode
- establish de-selection of Elements

**Comment by TimSusa** [comment]
As clarified, I will investigate for a mutli copy mode, which will be separated from the settings mode changes.

**Comment by TimSusa** [comment]
fixed with 1.3.40-alpha.4
