### ISSUE TITLE
BUG - Copy To Last Page causing setting errors

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#187]
**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.27

**Describe the bug**
The "Copy To Last Page" function is causing errors on exisiting Elements. I experienced even the reversion of settings on about 12 elements, that I've made in their Settings dialogues before copying a single element to last page. 

**Desktop Version (please complete the following information):**
 - OS: Win10

**Additional context**
Reffering to #184 the whole Select & Copy function needs to be excluded before release and then maybe rewritten entirely.

**Comment by TimSusa** [comment]
Elements will now be copied to the maximum right or bottom end of the page, so no confusional distribution of the current elements can happen. See 1.3.39-alpha.10
