### ISSUE TITLE
CPU Load (again)

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#188]
Lately I updated my preset with several new elements (about 25 elements per page, summed up about 100) and then experienced Audio Dropouts on my liveset, that I didn't have before. Many tests pointed me to the only originator: MIDI Bricks (sorry to say that!). I can simply see it in the Windows Resource Monitor, that everytime when I move a Slider in MIDI-Bricks, at least one of my system's processor core's load rising significantly: 
Having just one Slider in MIDI Bricks' Layout + being in LIVE Mode, on my desktop PC (i9-7900X 10-core at 4GHz) it's a 10-50% rise, on my Live-Notebook (i7 4-core) it's accordingly higher. LIVE Mode not activated causes almost double load. Occuring in the Electron App as well as in Web App on Chrome (while Chrome has a higher basic load). 

Right now I can only dodge the audio dropouts, when I increase the audio buffer of my soundcard to 512 samples - which causes frustrating high latency for my liveset. Maybe we can start to figure out, if it's caused by the Slider itself or Chrome/Electron or if there is any new idea to lower CPU load. 

**Does the issue occur in the electron-app or the web-app?**
- [ ] midi-bricks-electron
- [ ] midi-bricks-web-app
- [x] both

**Can you determine, which version was used?**
Version: 1.3.27 and 1.3.28

**Desktop Version (please complete the following information):**
 - OS: Win 10
 - Browser: Google Chrome
 - Version: newest

**Comment by TimSusa** [comment]
Can you please try out 1.3.32? Otherwise reopen this issue, if reproduced with that new version, please!
