### ISSUE TITLE
BUG - CC# not higher than 119

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#196]
**Can you determine, which version was used?**
Version: 1.3.27

**Describe the bug**
In a CC Element's settings it is not possible to set a higher CC number than 119. 

**Steps To Reproduce**
1. Create an Element
2. open its Settings dialog
3. try to enter a CC number higher than 120

**Expected behavior**
It should be possible to set CC numbers up to 127, right?

**Comment by TimSusa** [comment]
Yea, that is an issue, we already had in the past. The webmidi library throws an error, if I deliver values over 120. Please see the attached screenshot. I mean, if this is a real blocker for you, we should reach out to @djipco and ask him about that. Maybe this is standard MIDI behaviour? I don´t know?

<img width="839" alt="Screenshot 2020-08-01 at 16 19 19" src="https://user-images.githubusercontent.com/8963529/89103549-e2ee7680-d412-11ea-9ac0-87abc511bba0.png">

**Comment by TimSusa** [comment]
I have added an issue with the question to @djipco. Hopefully, he will answer. 

JFI
https://github.com/djipco/webmidi/issues/118

**Comment by TimSusa** [comment]
@alectroniq jfi https://github.com/djipco/webmidi/issues/118#issuecomment-667584421

**Comment by TimSusa** [comment]
As it is part of specification I would close this issue. Please be reffered @alectroniq jfi djipco/webmidi#118 (comment)
