### ISSUE TITLE
[FEATURE] save in preset: layout mode settings + theme

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#2]
should be stored in preset as well: 
- _Compact Horizontally_ or _Vertically_ selection in layout mode
- _Auto Arrange_ Mode in layout mode
- _Theme_ selection

Because: if you load a preset and enter layout mode with wrong _Compact_ mode selected and _Auto Arrange_ activated, the entire layout gets re-arranged.

**Comment by TimSusa** [comment]
I had a telephone call to https://github.com/HaNdTriX and we will try to find a way to synchronize state changes coming from electron process publishing to the renderer process state (maybe via ipc).

**Comment by TimSusa** [comment]
We have now fixed this inc new cool features. https://github.com/TimSusa/midi-bricks-mono/pull/125 which will to into release v.1.1.91
