### ISSUE TITLE
Feature - make MIDI Input Listener Sample Rate definable

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#214]
**Is your feature request related to a problem? Please describe.**
#208 

**Describe the solution you'd like**
Make the Sample Rate of the MIDI Input Listener adjustable in the Settings and save this Setting within the Preset. Label the settings with a tooltip, like "Increase if sliders display incoming MIDI Controller positions with a time lag. Decrease for smoother and more accurate slider movements."

**Comment by TimSusa** [comment]
Please test Version v1.3.39-alpha.3

**Comment by alectroniq** [comment]
It works. Two problems: 
- when entering delay values into the Preferences dialog, the dialog closes immediately (but still saves the value)
- when I play around with the value in action while using the app, the MIDI input slows down and seems to confuse things

**Comment by alectroniq** [comment]
1.3.39-alpha4: At the beginning it works fine. Then, while using the app, switching pages etc. the MIDI input latency starts to increase (in my case up to 2 sec during 1 minute of heavy performance). Then altering the Input delay doesn't change anything - the app still takes 2 sec to display incoming MIDI messages.

**Comment by TimSusa** [comment]
I put in a notification to save and reload your preset. if problems occur. Available since alpha 5

**Comment by alectroniq** [comment]
Works fine. But your current tooltip text is kind of weird and confusing for laymen. I suggest to change it to something like this (feel free to change wordings):

> Increase to >10 or >15, if incoming MIDI data is displayed with a lag on your system (caused by high amounts of data). Otherwise you can set lower values around 5 to display incoming MIDI data immediately and accurately for softer slider movements.

**Comment by TimSusa** [comment]
fixed in 1.3.40-alpha.0 and above. By the way, please open a new ticket for such issues in the future and connect it via #214 for example. Thx! Never forget: A reopened ticket is some kind of very very bad thing.
