### ISSUE TITLE
BUG - Horizontal Slider: range limits break slider function

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#223]
**Can you determine, which version was used?**
Version: 1.3.39-alpha4

**Describe the bug**
As soon as user defines a range for a Horizontal Slider, this breaks the function of the slider. On tap/click the Slider's thumb just jumps to the right.

**Steps To Reproduce**
1. Create a Slider
2. Open it's Settings Dialog
3. Change the Output Values (min/max)
4. Exit Settings Dialog
5. Try to operate the Slider

**Comment by TimSusa** [comment]
should be fixed with "1.3.39-alpha.6"
