### ISSUE TITLE
BUG - Horizontal Slider: container format

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#224]
**Can you determine, which version was used?**
Version: 1.3.39-alpha4

**Describe the bug**
In Layout Mode the container of a Horizontal Slider has a different format, than the Slider itself: the Slider is much flatter than the container. This wastes space in your layout and also causes Elements overlap.

**Steps To Reproduce**
1. Create Horizontal Slider
2. Change the size and format of the Slider

**Comment by TimSusa** [comment]
Fixed from 1.3.39-alpha.6 and higher
