### ISSUE TITLE
BUG - Sliders: Label is hidden when "Hide Label" is active

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#225]
**Can you determine, which version was used?**
Version: 1.3.39-alpha4

**Describe the bug**
When the value of a Slider is hidden, the Label gets hidden as well.

**Steps To Reproduce**
1. Create a Slider
2. Open its Settings dialog
3. In "View" activate "Hide Value"
4. See: the Slider's Label is gone

**Expected behavior**
The Slider's Label should remain as "Hide Value" is active.
Maybe create an extra option for "Hide Label"? This would be useful for the layout process!

**Comment by TimSusa** [comment]
fixed with "version": "1.3.39-alpha.6"
