### ISSUE TITLE
BUG - Max/Min Value Increase causes dialog to close

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#226]
**Can you determine, which version was used?**
Version: 1.3.39

**Describe the bug**
When altering the Maximum and Minimum Values of an Element's Output through the arrows, the dialog window gets closed after 2 clicks. 

**Additional context**
If the solution is laborious, just kill those arrow buttons. Entering numbers works as well :)

**Comment by TimSusa** [comment]
fixed in 1.3.40-alpha.4
