### ISSUE TITLE
BUG - fit Slider range to entire Slider length

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#227]
**Can you determine, which version was used?**
Version: 1.3.39

**Describe the bug**
When a Slider has a defined range (min. >0 and/or max. <127), the Slider just stops at this value position. 

**Expected behavior**
The full lenght of a Slider should be used for the defined control range.

**Additional context**
We've had this issue several times before and I hope this is not an endless back and forth of a fix of a fix of a fix of a fix... ? :-/

**Comment by TimSusa** [comment]
fixed in 1.3.40-alpha.5
