### ISSUE TITLE
Element Settings: Input Field - Enter closes Settings dialog

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#229]
Version: 1.3.40-alpha6

When entering text or numbers into Input fields, ENTER should confirm the input according to the OK button, instead of closing the Settings dialog window.

ENTER should also confirm a colour selection, not close its superior Settings dialog window.

**Comment by TimSusa** [comment]
valid point

**Comment by TimSusa** [comment]
Dialog is closed now with escape button. Feature availlable in v1.3.41.alpha-1
