### ISSUE TITLE
Feature - range inputs allow <0 and >127

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#230]
**Can you determine, which version was used?**
Version: 1.3.40-alpha6

Element Settings dialog - the input fields of Minimum and Maximum allow numbers lower than 0 and higher than 127. After closing the Settings dialog they fall back within that 0-127 range (which is good). But this should already occur on clicking OK. We have an inconsitent behaviour now, sometimes OK corrects the value, sometimes it doesn't.

And it shouldn't be possible to exceed the range with the arrow button on the input fields.

**Comment by TimSusa** [comment]
Fixed in 1.3.41-alpha.2
