### ISSUE TITLE
Element Settings dialog - don't disappear and close tabs on OK

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#231]
**Can you determine, which version was used?**
Version: 1.3.40-alpha6

When confirming an input with OK button, the dialog should not disappear and also should not close the tabs you just edited within the dialog window.

**Comment by TimSusa** [comment]
fixed in https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.3.41.alpha-0
