### ISSUE TITLE
BUG - "Copy To Last Page" destination page

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#234]
**Can you determine, which version was used?**
Version: 1.3.40-alpha6

**Describe the bug**
In Settings Mode the "Copy To Last Page" command does not copy to last page, but to next page. 
This behaviour is inconsitent: in some rare cases I found the copy on the last page. 

**Expected behavior**
Behavior according the command.

**Feature Request**
Establish a "Copy To..." command, which opens a selector for the destination page.

**Comment by TimSusa** [comment]
this is more a feature request. as i promised this will be closed, cause this is not bug!

**Comment by alectroniq** [comment]
I suggested a Feature in order to solve a problem, which I called a Bug. So I guess it's "invalid"?

**Comment by TimSusa** [comment]
fixed by 1.3.41-alpha.0
