### ISSUE TITLE
BUG - "Copy To Last Page" only works in Multi Selection Mode

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#235]
**Can you determine, which version was used?**
Version: 1.3.40-alpha6

**Describe the bug**
"Copy To Last Page" command appears when selecting a single Element. But here the command does not work. It only works when you apply it in the Multi Seletion Mode.

**Expected behavior**
Also make it work in normal Settings Mode, apart from Multi Mode Selection.

**Comment by TimSusa** [comment]
No!
