### ISSUE TITLE
BUG - How to confirm "Copy To Last Page" command?

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#236]
**Can you determine, which version was used?**
Version: 1.3.40-alpha6

**Describe the bug**
I'm unable to reliably confirm the "Copy To Last Page" command. 
Is it confirmed, when I exit Multi Selection Mode or when I exit Settings Mode?
The behaviour is inconsistent here.

Connected with issue #235

**Comment by TimSusa** [comment]
this is a question or more a feature request. no bug. sorry i close this
