### ISSUE TITLE
BUG - Settings Mode: selecting another Page pretends to change the actual page

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#237]
**Can you determine, which version was used?**
Version: 1.3.40-alpha6

**Describe the bug**
When clicking on a Page in Settings Mode, it's not clear if you just select and edit a Page, or if you switch to that Page at the same moment. Anyway the following action causes an unwanted duplicate:

**Steps To Reproduce**
1. Create several Pages
2. Go to Settings Mode
3. Click on a different Page (2) than the current one (1)
4. Close Page Settings dialog
**Question:** did this switch the Pages within Settings Mode? 
5. Exit Settings Mode
6. Switch between Pages and compare. See: one Page (1) has been duplicated to the other one (2).

**Comment by TimSusa** [comment]
your right. this is a logical problem. I suggest to put an extra caret to the page buttons, to open the settings, so that the origin focus to the actual page does not change.

**Comment by TimSusa** [comment]
Now the whole page is changed, when opening settings from another page. So the GUI confusion will not happen anymore. Fixed in 1.3.40
