### ISSUE TITLE
BUG - Preset save detection occationally detecting wrong save status

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#244]
**Can you determine, which version was used?**
Version: 1.3.41

**Describe the bug**
The save reminder doesn't detect saved/unsaved status right. This behaviour is not reproducable by 100%. Sometimes it works correctly, sometimes not. I can't see any depency.

**TRY To Reproduce**

1. save a preset
2. close app
3. see: reminder says "you have unsaved work"

- or -

1. modify a saved preset
2. do not save it
3. close the app
4. see: reminder does not remind me of unsaved work

**Comment by alectroniq** [comment]
disfunction only when Layout Mode is not entered during editing

**Comment by TimSusa** [comment]
please check with 1.3.41.alpha-2
