### ISSUE TITLE
IMPROVE - remain Undo button on position

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#245]
The Undo button changes its position in several modes, e.g. it appears somewhere else in Layout Mode, than in Settings Mode. Remain it on its initial, fixed position. Even if other buttons appear and disappear while going back through Undo steps, it should not move. Because when a user goes through Undo steps, he's watching the screen while clicking on Undo blindly.

**Comment by TimSusa** [comment]
fixed https://github.com/TimSusa/midi-bricks-mono/releases/tag/v1.3.42
