### ISSUE TITLE
[FEATURE] MIDI Driver settings: mark drivers & channels used in preset

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#3]
**must:** In MIDI Driver settings mark Drivers and Channels, that are used in the current preset. Use a color for this, maybe blue?

**should:** In Global Settings View mark Elements with a color, which use a deactivated Driver or Channel.

**could:** In MIDI Driver settings display a warning, when deactivating Drivers or Channels, that are used in Elements of the current preset.

**Comment by TimSusa** [comment]
should be fixed
