### ISSUE TITLE
[BUG] window size+position is not saved

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#32]
**Does the issue occur in the electron-app or the web-app?**
- [X] midi-bricks-electron
- [ ] midi-bricks-web-app
- [ ] I do not know nor understand

**Can you determine, which version was used?**
Version: 0.12.44

**Describe the bug**
The size and position of the App window is neither saved by saving the preset, nor saved by closing the App. 

**Steps To Reproduce**
1. set custom window size + position
2. save preset
3. close app
4. re-open app
5. load preset
6. see a different window size + position

**Expected behavior**
Window size and position should be saved with the preset, but not when closing the App. 

**Desktop Version (please complete the following information):**
 - OS: Win 10 64bit
 - Browser: (electron app)

**Comment by TimSusa** [comment]
We try to update module https://github.com/mawie81/electron-window-state/releases to actual release, where a fix for multi-device issue. Would you please check release 0.12.50?

**Comment by alectroniq** [comment]
Checked on 0.12.53 and also 0.12.63: Window size + position is _not_ saved. Neither with preset, nor when closing the app.
