### ISSUE TITLE
[BUG] MIDI listener performance

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#33]
**Does the issue occur in the electron-app or the web-app?**
- [X] midi-bricks-electron
- [ ] midi-bricks-web-app
- [ ] I do not know nor understand

**Can you determine, which version was used?**
Version: 0.12.44

**Describe the bug**
Bad and jittery MIDI listener performance, just as we had some time ago. Cannot clearly reproduce concrete conditions: once it works fine and smooth, next time it doesn't. Seems to interfere with Preset loading. 

**Steps To Reproduce**
1. create large preset with many elements (ca. 100). include several elements with MIDI listener on CCs of an external MIDI device. 
2. save preset and close app
3. re-open app and load preset
4. test performance of the MIDI listeners
5. close and re-open the app again
6. test performance
7. load preset and test performance
8. does it always perform well? 

**Expected behavior**
always, termless good performance

**Desktop Version (please complete the following information):**
 - OS: Win 10 64bit
 
**Additional context**
@TimSusa hatte dir den Fehler schonmal am 6.2. beschrieben

**Comment by alectroniq** [comment]
**additional information:** 
this issue is not only related to preset loading. 

**steps to reproduce:**
1. Open the Electron app, my previous preset is automatically loaded and LIVE mode is active. Listener performance is fine. 
2. Deactivate LIVE mode: Listener performance is bad!
3. Reactivation of LIVE mode **does not help**. 
4. Close App, reopen and stay in LIVE mode (no preset load etc.): performance is fine.

**Comment by alectroniq** [comment]
I'm sorry, but I note that the condition in my last comment above is not consistent, too. 
@TimSusa : let's have a phone call next week and sort it out :)

**Comment by TimSusa** [comment]
Hey, just please try to change the footer page, after you have set to live mode. This should extract the page from the big state and performance should be fine.

**Comment by alectroniq** [comment]
Tested on 0.12.53. The problem still is:
After loading a preset, the performance is bad. Even in LIVE mode, after switching pages in the footer.

I'm desperate, because there is no consistent condition for clear reproduction: Like in 90% the performance is fine after opening the App without loading a preset. And in 10% the it's fine after loading a preset.

**Comment by TimSusa** [comment]
Maybe, it is an issue with timing or better said events, which are waiting in the queue, where afterwards the digest cycle went further. So would you try to do the actions delayed by some kind of seconds and never ever trigger a midi event from the hardware, before switching to live mode? Maybe wait for 3-5 sec until switching to livemode and after that waiting again when switching footer pages. Do you obtain different behaviour?

**Comment by alectroniq** [comment]
Sheeeeeeesh, this is solved in 0.12.66! Sliders controlled by external MIDI hardware are running super smooth!
After opening the app, before and after loading presets and even when not being in LIVE mode - always smooth. 
Thanks so much!

**Comment by TimSusa** [comment]
I like to hear from this!
