### ISSUE TITLE
[FEATURE] Load Preset: only .js files

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#34]
**Is your feature request related to a problem? Please describe.**
(I'm always frustrated when...) I'm looking for my preset and scroll through my folders to find it.

**Describe the solution you'd like**
Filter the load/open dialog for .js files. 

No big deal, just a little help :)

**Comment by TimSusa** [comment]
What about creating an extra Folder for only that presets? This should provide you with less frustration.

**Comment by alectroniq** [comment]
Possible, but less comfy :) If this is a big deal for you, feel free to close this issue.

**Comment by TimSusa** [comment]
Hey, now we have established communication via IPC (inter process communication) between renderer (React) and main (Electron) process, which enables configuring the electron app file loading dialog and getting the results from there. As a nice to have, you now have filters for *.js and *.json files. Furthermore loading of json files for electron app should be enabled. Please test version 1.0.9. I will close this issue.
