### ISSUE TITLE
[IMPROVE] wordings

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#4]
To be discussed here: better wordings for... 

- Elements/Objects/**Controllers**? (Sliders and Buttons, created in a Layout)
- Global Settings --> Controllers Overview/List
- Restore Values --> Restore Saved Values
- Compact Vertically/Horizontally --> Gravity: top / Gravity: left
- the name of our App :)

**Comment by TimSusa** [comment]
should be fixed
