### ISSUE TITLE
Layout changes partly unsaved after leaving layout mode

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#50]
**Does the issue occur in the electron-app or the web-app?**
- [x] midi-bricks-electron
- [ ] midi-bricks-web-app
- [] I do not know nor understand

**Can you determine, which version was used?**
Version: 0.12.53

**Describe the bug**
In Layout mode i move elements. When pressing X to leave Layout mode, some elements jump back to their previous position.

**Steps To Reproduce**
1. Enter Layout mode.
2. Move elements.
3. Leave Layout mode.
4. See elements jumping back. 

**Expected behavior**
Elements should stay, where I told them to sit ;)

**Desktop Version (please complete the following information):**
 - OS: Win 10

**Comment by TimSusa** [comment]
Now you have a check button for taking over changes and some cancel button to go back to the layout you had before.

**Comment by alectroniq** [comment]
I don't find a check button to save changes, but I'd prefer to have it. Just to keep everything logic and clear for everyone. But though still keep it the way it is: save changes when leaving layout mode (by click or shortcut L).
Also the "Go back" tooltip should be "cancel" or "discard changes".

**Comment by alectroniq** [comment]
great now (0.12.73)
