### ISSUE TITLE
MIDI learn: assign learned parameter to Output

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#54]
**Does the issue occur in the electron-app or the web-app?**
- [x] midi-bricks-electron
- [ ] midi-bricks-web-app
- [ ] I do not know nor understand

**Can you determine, which version was used?**
Version: 0.12.63

**Describe the bug**
MIDI learn assigns the Input of an Element to the learned CC#, which is good, but...

**Expected behavior**
MIDI Output should **also** be assigned to this learned CC#, which is the actual purpose of MIDI learn.

**Comment by TimSusa** [comment]
we should have fixed that by 0.71

**Comment by alectroniq** [comment]
works
