### ISSUE TITLE
"Delete All" doesn't delete page buttons

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#68]
**Does the issue occur in the electron-app or the web-app?**
- [x] midi-bricks-electron
- [ ] midi-bricks-web-app
- [ ] I do not know nor understand

**Can you determine, which version was used?**
Version: 0.12.71

**Describe the bug**
after using "Delete All" the footer still contains all page buttons

**Comment by TimSusa** [comment]
fixed by 0.14.10
