### ISSUE TITLE
[FEATURE] establish MIDI Learn on Listener

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#7]
Nice to have: 
Establish a "MIDI Learn" button next to the "Listen to CC" menu of an element. This function would recognize incoming MIDI data (for instance "Diver: Circuit, MIDI Ch.: 2, CC#: 80") and automatically apply this data to the Listener setting. 

Why? 
Because any MIDI hardware has huge MIDI Implementation charts for their MIDI mappings, that you cannot access always, anytime and anywhere. So you'd depend on such a MIDI Learn feature, if you don't have access to a specific MIDI Implementation chart.

**Comment by TimSusa** [comment]
Should be established.
