### ISSUE TITLE
Controllers overview: filename incorrect

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#70]
In "Controllers" overview the header displays an incorrect filename. It only updates after loading a preset.
Expected: update filename after saving a preset.

**Comment by TimSusa** [comment]
I had a telephone call to https://github.com/HaNdTriX and we will try to find a way to synchronize changes coming from electron process publishing to the renderer process (maybe via ipc).

**Comment by TimSusa** [comment]
Ok this is fixed in version 1.0.10. Tested on Win 7.
