### ISSUE TITLE
[FEATURE] saved value: optional mark/hint at slider + reset button

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-bricks-mono#8]
The value of an element, that's saved with a preset, should be available beside/below a slider itself like this:
![saved value](https://user-images.githubusercontent.com/43702087/48951590-67e77400-ef3f-11e8-90be-74f0c7b4aa2f.png)
(this image already has Current Value position, as suggested in #79 )

- an optional mark that shows the saved value on a slider graphically (if realisable)
and/or
- an optional value display below the current value

both to be activated in Settings dialog below "hide value":
- show saved value mark
- show saved value

reset function: 
by tapping on the mark or the value at the bottom, you'd be ableto reset the slider to this saved value/position.

**Comment by TimSusa** [comment]
Resetting is possible by clicking just on the value label. Fixed with: https://github.com/TimSusa/midi-sliders/commit/0c444a27d6d895a04cc400aaa6dae1a5ce08f2bf

**Comment by TimSusa** [comment]
Feature is estbalished with 0.12.32
